import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles/styles.css";

const API="/api";
const nav=[["Services","/services/"],["Solutions","/solutions/"],["Industries","/industries/"],["SAP Expertise","/sap-expertise/"],["Case Studies","/case-studies/"],["About","/about/"],["Insights","/insights/"]];
const outcomes=[["Modernize","Modernize legacy SAP landscapes."],["Integrate","Connect SAP with the wider enterprise ecosystem."],["Optimize","Improve business processes and system performance."],["Scale","Build scalable enterprise architecture."],["Operate","Keep SAP reliable through structured support and managed services."],["Innovate","Use BTP, data, automation, and AI where they create measurable value."]];

function Header(){const [open,setOpen]=useState(false);return <header id="site-header" className="sticky top-0 z-[200] border-b border-gray-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-6"><a href="/" className="text-lg font-semibold tracking-tight text-navy-950 sm:text-xl">Luminous Consulting</a><nav className="hidden items-center gap-1 lg:flex" aria-label="Primary">{nav.map(([label,url])=><a key={url} href={url} className="rounded-md px-3 py-2 text-sm font-medium text-ink transition-colors hover:text-accent">{label}</a>)}</nav><a className="hidden rounded-md bg-accent px-5 py-2.5 text-sm font-medium text-white hover:bg-accent-dark lg:block" href="/contact/">Talk to an SAP Expert</a><button id="mobile-menu-toggle" onClick={()=>setOpen(!open)} className="relative z-[220] flex h-11 w-11 items-center justify-center rounded-md bg-transparent text-navy-950 lg:hidden" aria-expanded={open} aria-label={open?"Close navigation menu":"Open navigation menu"}><span className="text-2xl">{open?"×":"☰"}</span></button></div>{open&&<aside className="fixed inset-y-0 right-0 z-[150] flex h-[100dvh] w-[min(88vw,390px)] flex-col overflow-y-auto border-l border-gray-200 bg-white px-6 pb-8 pt-24 shadow-2xl lg:hidden"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Navigation</p><p className="mt-2 text-sm leading-6 text-ink/65">Explore our SAP services, solutions and expertise.</p><nav className="mt-6 flex flex-col">{nav.map(([label,url])=><a key={url} href={url} onClick={()=>setOpen(false)} className="border-b border-gray-200 py-4 text-base font-medium text-navy-950 hover:text-accent">{label}</a>)}</nav><a href="/contact/" className="mt-auto rounded-md bg-accent px-5 py-3 text-center text-sm font-medium text-white">Talk to an SAP Expert</a></aside>}</header>}

function Footer(){return <footer className="border-t border-gray-200 bg-navy-950 text-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 md:py-20"><div className="grid gap-10 md:grid-cols-12"><div className="md:col-span-4"><a href="/" className="text-xl font-semibold tracking-tight">Luminous Consulting</a><p className="mt-4 max-w-sm text-sm leading-6 text-white/65">SAP consulting for transformation, integration, development, data and managed services. Clear advice, practical delivery.</p><a href="/contact/" className="mt-6 inline-flex text-sm font-semibold hover:text-white/80">Start a conversation →</a></div><div className="md:col-span-8"><div className="grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-4">{nav.map(([label,url])=><div key={url}><p className="text-sm font-semibold">{label}</p><a href={url} className="mt-4 block text-sm text-white/60 hover:text-white">Explore {label}</a></div>)}</div></div></div><div className="mt-14 border-t border-white/10 pt-7 text-xs text-white/45">© {new Date().getFullYear()} Luminous Consulting. All rights reserved.</div></div></footer>}

function Layout({children,title,description}:{children:React.ReactNode,title?:string,description?:string}){useEffect(()=>{document.title=title||"Luminous Consulting | SAP Consulting";let m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement("meta");m.setAttribute("name","description");document.head.appendChild(m)}m.setAttribute("content",description||"SAP consulting, S/4HANA transformation, integration, development and managed services for enterprise SAP landscapes.")},[title,description]);return <><Header/><main id="main-content">{children}</main><Footer/></>}

function CTA(){return <section className="bg-navy-950 text-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 md:py-20"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-white/60">Start a conversation</p><h2 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">Have an SAP challenge to solve?</h2><p className="mt-4 text-base leading-7 text-white/70">Tell us what you're trying to solve and we'll follow up with the right SAP specialist.</p><a href="/contact/" className="mt-7 inline-flex rounded-md bg-white px-5 py-3 text-sm font-semibold text-navy-950 hover:bg-gray-50">Talk to an SAP Expert →</a></div></div></section>}

function Home(){return <Layout title="Luminous Consulting | SAP Consulting, S/4HANA, BTP & Integration"><section className="border-b border-gray-200 bg-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-6 md:grid-cols-2 md:items-center md:py-24"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-accent">SAP consulting & transformation</p><h1 className="mt-4 text-4xl font-semibold tracking-tight text-navy-950 md:text-6xl">Make SAP simpler. Build what the business needs next.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/70">Luminous Consulting helps businesses simplify SAP with S/4HANA transformation, SAP BTP, integration, development, data and managed services.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/contact/" className="rounded-md bg-accent px-5 py-3 text-sm font-semibold text-white hover:bg-accent-dark">Talk to an SAP Expert</a><a href="/services/" className="rounded-md border border-gray-200 px-5 py-3 text-sm font-semibold text-navy-950 hover:border-accent/40">Explore services</a></div></div><div className="hidden md:block"><div className="rounded-lg border border-gray-200 bg-gray-50 p-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-accent">Practical SAP delivery</p><div className="mt-8 space-y-5">{["Advisory","Transformation","Integration","Development","Data & AI","Managed Services"].map((x,i)=><div key={x} className="flex items-center gap-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-navy-950 text-xs font-semibold text-white">{String(i+1).padStart(2,"0")}</span><span className="font-medium text-navy-950">{x}</span></div>)}</div></div></div></div></section><section className="border-b border-gray-200 bg-gray-50"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 md:py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{outcomes.map(([n,d],i)=><div key={n} className="rounded-lg border border-gray-200 bg-white p-6"><span className="text-sm font-semibold text-accent">{String(i+1).padStart(2,"0")}</span><h2 className="mt-4 text-lg font-semibold text-navy-950">{n}</h2><p className="mt-2 text-sm leading-6 text-ink/70">{d}</p></div>)}</div></div></section><ContentTeasers/><CTA/></Layout>}

function ContentTeasers(){const [services,setServices]=useState<any[]>([]);useEffect(()=>{fetch(API+"/services").then(r=>r.ok?r.json():[]).then(x=>setServices(Array.isArray(x)?x.slice(0,6):[])).catch(()=>{})},[]);return <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 md:py-20"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-accent">Services</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy-950 md:text-4xl">SAP work that starts with the business problem.</h2><p className="mt-4 text-base leading-7 text-ink/70">Choose a starting point. We keep the technology language clear, then build the right delivery path.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><a key={s.slug||i} href={"/services/"+s.slug+"/"} className="rounded-lg border border-gray-200 p-6 hover:-translate-y-0.5 hover:border-accent/40 hover:shadow-md"><span className="text-sm font-semibold text-accent">{String(i+1).padStart(2,"0")}</span><h3 className="mt-4 text-lg font-semibold text-navy-950">{s.name}</h3><p className="mt-2 text-sm leading-6 text-ink/70">{s.shortSummary||s.heroIntro||""}</p><span className="mt-5 inline-flex text-sm font-semibold text-accent">Explore service →</span></a>)}</div></div></section>}

function Listing({kind,label,title,description}:{kind:"services"|"solutions"|"industries"|"case-studies"|"insights",label:string,title:string,description:string}){const [items,setItems]=useState<any[]>([]);useEffect(()=>{fetch(API+"/"+kind).then(r=>r.json()).then(x=>setItems(Array.isArray(x)?x:[])).catch(()=>setItems([]))},[kind]);return <Layout title={title} description={description}><section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-4xl px-5 py-14 text-center sm:px-6 md:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">{label}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-navy-950 md:text-5xl">{title.split(" | ")[0]}</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-ink/70 md:text-lg">{description}</p></div></section><section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-6 md:py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><a key={x.slug||i} href={"/"+kind+"/"+x.slug+"/"} className="group rounded-lg border border-gray-200 bg-white p-6 transition-all hover:-translate-y-0.5 hover:border-accent/40 hover:shadow-md"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-accent">{String(i+1).padStart(2,"0")}</p><h2 className="mt-2 text-xl font-semibold leading-7 text-navy-950 group-hover:text-accent">{x.name||x.title||x.heading}</h2><p className="mt-3 text-sm leading-6 text-ink/70">{x.shortSummary||x.summary||x.description||""}</p><span className="mt-5 inline-flex text-sm font-semibold text-accent">Explore →</span></a>)}</div></div></section><CTA/></Layout>}

function Section({heading,children,gray=false}:{heading:string,children:React.ReactNode,gray?:boolean}){return <section className={gray?"border-y border-gray-200 bg-gray-50":"border-b border-gray-200 bg-white"}><div className="mx-auto max-w-4xl px-6 py-14 md:py-16"><h2 className="text-2xl font-semibold tracking-tight text-navy-950 md:text-3xl">{heading}</h2><div className="mt-5 text-base leading-7 text-ink/75">{children}</div></div></section>}
function Detail({kind,slug}:{kind:string,slug:string}){const [item,setItem]=useState<any>(null);useEffect(()=>{fetch(API+"/"+kind+"/"+slug).then(r=>r.ok?r.json():null).then(setItem).catch(()=>setItem(null))},[kind,slug]);if(!item)return <Layout><section className="mx-auto max-w-3xl px-6 py-24 text-center"><h1 className="text-3xl font-semibold text-navy-950">Loading…</h1></section></Layout>;
const title=item.name||item.title; const list=(section:string)=>item.listItems?.filter((x:any)=>x.section===section)||[];
const items=(xs:any[],heading:string,gray=false)=><Section heading={heading} gray={gray}><ul className="grid gap-3 sm:grid-cols-2">{xs.map((x:any)=><li key={x.id} className="rounded-md border border-gray-200 bg-white px-4 py-3">{x.text}</li>)}</ul></Section>;
return <Layout title={(item.metaTitle||title)+" — Luminous Consulting"} description={item.metaDescription||item.shortSummary}><section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-4xl px-6 py-16 md:py-20"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-accent">{kind==="case-studies"?"Representative SAP use case":kind==="insights"?item.category:"SAP consulting"}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-navy-950 md:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-ink/70">{item.heroIntro||item.summary||item.shortSummary}</p><a href="/contact/" className="mt-7 inline-flex rounded-md bg-accent px-5 py-3 text-sm font-semibold text-white hover:bg-accent-dark">{item.ctaLabel||"Talk to an SAP Expert"}</a></div></section>
{kind==="services"&&<><Section heading="The business problem">{item.businessProblem}</Section>{items(list("what_we_solve"),"What we solve",true)}{items(list("capabilities"),"Capabilities")}{items(list("technology"),"Technology",true)}<Section heading="Delivery approach">{item.deliveryApproach}</Section>{items(list("deliverables"),"Deliverables",true)}<Section heading="Engagement model">{item.engagementModel}</Section><Section heading="Who it's for" gray>{item.whoItsFor}</Section></>}
{kind==="solutions"&&<><Section heading="The business challenge">{item.businessProblem}</Section>{items(list("what_this_includes"),"What this includes",true)}<Section heading="Our approach">{item.approach}</Section>{items(list("outcomes"),"Outcomes addressed",true)}<Section heading="Who it's for">{item.whoItsFor}</Section></>}
{kind==="industries"&&<>{items(list("challenges"),"Industry challenges")}{items(list("processes"),"Business processes",true)}<Section heading="SAP landscape">{item.sapLandscape}</Section>{items(list("modules"),"Relevant SAP modules",true)}{items(list("integration_requirements"),"Integration requirements")}{items(list("transformation_opportunities"),"Transformation opportunities",true)}{items(list("typical_use_cases"),"Typical use cases")}<Section heading="Outcomes">{item.outcomes}</Section></>}
{kind==="case-studies"&&<><Section heading="Business challenge">{item.businessChallenge}</Section><Section heading="Objective" gray>{item.objective}</Section><Section heading="Approach">{item.approach}</Section><Section heading="Solution" gray>{item.solution}</Section><Section heading="Technology used">{item.technologyUsed}</Section><Section heading="Outcome" gray>{item.outcome}</Section></>}
{kind==="insights"&&<><Section heading="Article">{item.content?.split("\n\n").map((p:string,i:number)=><p key={i} className="mb-5">{p}</p>)}</Section></>}
<CTA/></Layout>}
function Contact(){return <Layout title="Contact — Luminous Consulting"><section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-2xl px-6 py-16 text-center"><h1 className="text-4xl font-semibold tracking-tight text-navy-950">Tell us what you're trying to solve.</h1><p className="mt-4 text-lg leading-relaxed text-ink/70">Share a few details and we'll follow up with the right SAP specialist.</p></div></section><section className="bg-white"><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload=Object.fromEntries(f.entries());const r=await fetch(API+"/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(r.ok) window.location.href="/contact/thank-you/"; else alert("Please check your details and try again.")}} className="mx-auto max-w-2xl space-y-6 px-6 pb-20 pt-8"><div className="grid gap-6 sm:grid-cols-2">{["name","workEmail","company","jobTitle","country","phone","sapEnvironment","currentSapSystem","projectStage","timeline","estimatedScope"].map(n=><label key={n} className="text-sm font-medium text-ink">{n.replace(/[A-Z]/g,m=>" "+m)}<input name={n} required={["name","workEmail","company"].includes(n)} className="mt-2 w-full rounded-md border border-gray-200 px-4 py-2.5 text-sm focus:border-accent focus:outline-none" /></label>)}</div><label className="block text-sm font-medium text-ink">Required services<input name="requiredServices" className="mt-2 w-full rounded-md border border-gray-200 px-4 py-2.5 text-sm"/></label><label className="block text-sm font-medium text-ink">Message<textarea name="message" rows={6} className="mt-2 w-full rounded-md border border-gray-200 px-4 py-2.5 text-sm"/></label><button className="rounded-md bg-accent px-5 py-3 text-sm font-medium text-white hover:bg-accent-dark">Request consultation</button></form></section></Layout>}

function App(){const p=window.location.pathname.replace(/^\/+|\/+$/g,"");if(!p)return <Home/>;if(p==="contact")return <Contact/>;if(p==="services")return <Listing kind="services" label="SAP services" title="SAP services" description="Explore SAP consulting services including advisory, S/4HANA transformation, implementation, integration, development, data and managed services."/>;if(p==="solutions")return <Listing kind="solutions" label="SAP solutions" title="Solutions organized around business outcomes." description="Move from a technology challenge to a clear solution path across transformation, cloud, integration, automation, data and AI."/>;if(p==="industries")return <Listing kind="industries" label="SAP by industry" title="SAP by industry" description="The SAP challenges, processes, and modules that matter most vary by industry — this is where we apply the services and solutions above."/>;if(p==="case-studies")return <Listing kind="case-studies" label="Case studies" title="Case studies" description="Representative SAP use cases illustrating how these services and solutions come together in practice."/>;if(p==="insights")return <Listing kind="insights" label="Insights" title="Insights" description="Practical articles and guides on S/4HANA, integration, security, data, and the rest of the SAP landscape."/>;return <Home/>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
